---
title: "Chapter 4 - markdown file"
author: "Charles Suey"
date: "2023-12-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Regularization Summary 
- Loaded data containing semiconductor data.
- Fitted a logistic regression model (`glm`) with the dependent variable `FAIL` and all available predictors.
- Calculated and interpreted the pseudo-R-squared value for the logistic regression model.
- Defined custom functions for deviance and R-squared calculation, allowing for both Gaussian and binomial families.
- Conducted a K-fold cross-validation experiment for the logistic regression model
- Plotted a boxplot to visualize the distribution of R-squared values.
- Explored the average R-squared values obtained from the cross-validation experiment.
- Performed forward stepwise regression (`step`) as an example of variable selection.
- Installed and loaded the `gamlr` package for LASSO regression.
- Conducted K-fold cross-validation for LASSO (`cv.gamlr`), plotting the results.
- Extracted coefficients for the minimum selected model in LASSO.
- Explored Aikaike's Information Criterion (AIC) for each model in the LASSO path.

Extension
-For this weeks code I had allot of issues with many of the commands not working and was unable to successfully troubleshoot it resulting in errors in my code and added to my trouble comming up with an extension that didnt result in similar errors 
